# Generated by Django 2.2.12 on 2022-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BikeReg',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='bike_name',
        ),
        migrations.AddField(
            model_name='bike',
            name='owner_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
